App\Entity\Book:
    properties:
        title:
            - NotBlank: ~
            - Length:
                min: 3
                max: 250
                minMessage: 'Your first name must be at least {{ limit }} characters long'
                maxMessage: 'Your first name cannot be longer than {{ limit }} characters'
                allowEmptyString: false
